import Link from "./site-link";
import {ArrowUpRight, ArrowRight, ChevronRight, ChevronLeft, MoveUpRight, Sparkles, Asterisk, Headphones, Compass, Mail} from "lucide-react";
import {articles, orderedArticles, articleByKey, articleCategory, dateLabel, forCategory, bodies, type Article} from "@/app/data/content";
import {categories, categoryByKey, type Category} from "@/app/data/navigation";
import {Header} from "./site-header";
import {Brand} from "./brand";
import {NewsletterForm, ReaderActions} from "./reader-actions";
import {ReadingProgress} from "./reading-progress";
import {Wave, Squiggle} from "./wave";
import {AdSlot} from "./ad-slot";
import {Pagination, PaginationContent, PaginationItem, PaginationLink} from "@/components/ui/pagination";

function Photo({article,priority=false,className="",sizes="(max-width: 700px) 100vw, 50vw"}:{article:Article;priority?:boolean;className?:string;sizes?:string}) {
 return <img className={className} src={article.image} srcSet={`${article.imageSmall} 520w, ${article.image} 1280w`} sizes={sizes} alt={article.title} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'} decoding="async" width={1280} height={854}/>;
}
function Meta({article}:{article:Article}) {return <div className="story-meta"><time dateTime={article.date}>{dateLabel(article.date)}</time><span>·</span><span>{article.minutes} dk</span></div>}
export function StoryCard({article,variant='',priority=false,index}:{article:Article;variant?:string;priority?:boolean;index?:number}) {
 const cat=articleCategory(article);
 return <article className={`story-card ${variant}`} data-category={cat.key}><Link href={article.path} className="story-image" tabIndex={-1} aria-hidden="true"><Photo article={article} priority={priority}/>{index!==undefined&&<span className="card-number">0{index+1}</span>}<span className="image-arrow"><ArrowUpRight size={23}/></span></Link><div className="story-copy"><Link className="eyebrow" href={cat.path}>{cat.name}</Link><h3><Link href={article.path}>{article.title}</Link></h3>{variant==='feature'&&<p>{article.excerpt}</p>}<Meta article={article}/></div></article>;
}
function SectionHeading({title,link,eyebrow,accent}:{title:string;link?:Category;eyebrow?:string;accent?:string}) {return <div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}{accent&&<em>{accent}</em>}</h2></div>{link&&<Link className="all-link" href={link.path}>Hepsine bak <ArrowUpRight size={20}/></Link>}</div>}
function Footer() {return <>
 <section className="newsletter-section" id="bulten"><Wave className="newsletter-wave"/><div className="site-width newsletter-inner"><div className="newsletter-copy"><span className="eyebrow">GEL, BUNU DA KONUŞALIM.</span><h2>HAFTALIK<br/><span>DOZUN</span><br/>BURADA.</h2><div className="newsletter-stamp" aria-hidden="true">%100<br/>MERAK</div><p>İyi hikâyeler, yeni takıntılar, kaçırılmayacak keşifler.<br/>Haftada bir, doğrudan e-postana.</p></div><div className="newsletter-form-wrap"><span className="hand-note">Feed’in kaçırdıkları burada. <ArrowDownMark/></span><NewsletterForm/></div></div></section>
 <footer className="footer"><div className="site-width"><div className="footer-top"><div className="footer-manifesto"><span>HAYATIN İÇİNDEN.<br/>FEED’İN DIŞINDAN.</span><a className="publisher" href="https://hipmedya.com/" target="_blank" rel="noreferrer">Bir <strong>hip.</strong> medya yayını <ArrowUpRight size={16}/></a></div><div className="footer-links">{['yasam','ajanda','populer'].map(key=><div key={key}><Link className="footer-group" href={categoryByKey(key).path}>{categoryByKey(key).name}</Link>{categories.filter(c=>c.parent===key).slice(0,6).map(c=><Link key={c.key} href={c.path}>{c.name}</Link>)}</div>)}</div></div><div className="footer-wordmark"><Brand/><Asterisk aria-hidden="true"/></div><div className="footer-bottom"><span>© 2026 Hipinup.</span><div><a href="https://hipinup.com/hakkimizda/">Hakkımızda</a><a href="https://hipinup.com/iletisim/">İletişim</a><a href="https://hipinup.com/uyelik-aydinlatma-metni/">Gizlilik</a><a href="https://hipinup.com/gizlilik-politikasi/">Çerezler</a></div><a href="#top" className="back-top">Yukarı <MoveUpRight size={17}/></a></div><div className="prototype-note">Tasarım önizlemesi · Hipinup arşivinden içeriklerle hazırlanmıştır.</div></div></footer>
 </>}
function ArrowDownMark(){return <svg width="60" height="41" viewBox="0 0 60 41" fill="none" aria-hidden="true"><path d="M3 3C39 0 49 7 40 34M28 25l11 11 14-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>}
export function Shell({children}:{children:React.ReactNode}) {return <div id="top"><Header articles={orderedArticles}/>{children}<Footer/></div>}
function Radar() {return <div className="radar"><div className="site-width"><span className="radar-tag"><Sparkles size={16}/> RADARDA</span><div className="radar-topics"><Link href={articleByKey('tommy-t-wave').path}>T-WAVE ETKİSİ</Link><span>✳</span><Link href={categoryByKey('moda').path}>STİL KODLARI</Link><span>✳</span><Link href={categoryByKey('seyahat').path}>MOD: KAÇIŞ</Link><span>✳</span><Link href={categoryByKey('sanat').path}>ŞEHRİN SANATI</Link></div><span className="radar-edition">SEÇKİ / 01</span></div></div>}
function Marquee(){return <div className="culture-ticker" aria-label="Pop kültür, gerçek hayat, Hipinup"><div className="ticker-track">{[0,1].map(i=><div key={i} aria-hidden={i===1}><span>POP KÜLTÜR</span><Asterisk/><span className="ticker-outline">GERÇEK HAYAT</span><Asterisk/><span>BİRAZ HİPİNUP</span><Asterisk/></div>)}</div></div>}
export function HomePage() {
 const cover=articleByKey('freesbee');const travel=articleByKey('modern-travel');
 return <Shell><Radar/><main id="icerik">
 <div className="site-width masthead-ad"><AdSlot format="leaderboard"/></div>
 <section className="site-width cover-grid" aria-label="Kapak ve öne çıkanlar"><article className="cover-story"><Link href={cover.path} className="cover-stage"><Photo article={cover} priority/><span className="cover-kicker">STİL RADARI <ArrowUpRight size={17}/></span><span className="cover-star" aria-hidden="true">TAK<br/>TAVRINI.</span><h1><span>KALİFORNİYA</span><span>RUHUNU TAK.</span></h1><span className="cover-side-text" aria-hidden="true">NO RULES. JUST STYLE.</span></Link><div className="cover-description"><p>Cesur çerçeveler. Özgür ruhlar. Freesbee’nin Kaliforniya enerjisi şimdi Türkiye’de.</p><Link href={cover.path} className="round-link" aria-label="Freesbee hikâyesini oku"><ArrowUpRight size={26}/></Link></div><Meta article={cover}/></article>
 <aside className="hot-feed"><div className="hot-heading"><span className="eyebrow">BUNU DA BİL</span><h2>Akışta<br/><em>ne var?</em><Squiggle/></h2><span className="tiny-circle" aria-hidden="true">up!</span></div><div className="hot-feed-stories">{['tommy-t-wave','elif-ebru-sakar','david-lynch'].map((key,i)=><StoryCard key={key} article={articleByKey(key)} variant="feed-row" index={i}/>)}</div><Link href={travel.path} className="travel-teaser"><div><span className="eyebrow">SEYAHAT DOSYASI</span><h3>Az eşya.<br/>Çok hikâye.</h3><span>Hafif seyahat et <ArrowUpRight size={18}/></span></div><Photo article={travel}/></Link></aside></section>
 <section className="site-width quick-picks"><div className="quick-title">KAÇIRMA<Squiggle/></div>{['tags-design','bubas-bosphorus','istanbula-reverans'].map((key,i)=>{const a=articleByKey(key);return <Link href={a.path} key={key}><span className="quick-number">0{i+1}</span><div><span className="eyebrow">{articleCategory(a).name}</span><h3>{a.title}</h3></div><ArrowUpRight size={19}/></Link>})}</section>
 <Marquee/>
 <section className="site-width style-section"><div className="style-section-top"><span className="eyebrow">MODA & STİL / KENDİN GİBİ GİYİN</span><Link href={categoryByKey('moda').path} className="all-link">Stil dosyasını aç <ArrowUpRight size={19}/></Link></div><div className="style-spread"><div className="style-manifesto"><h2>ÇOK<br/><span>İYİ</span><br/>GÖRÜNÜYOR.</h2><Squiggle/><p>Trendler geçer.<br/>Tavrın kalır.</p><span className="style-note">Senin stilin,<br/>senin kuralların.</span></div><StoryCard article={articleByKey('certain-denim')} variant="fashion-big" index={0}/><StoryCard article={articleByKey('akay')} variant="fashion-arch" index={1}/><StoryCard article={articleByKey('sustainable-fashion')} variant="fashion-small" index={2}/></div></section>
 <div className="ad-break"><div className="site-width"><AdSlot format="billboard"/></div></div>
 <section className="escape-section"><Wave className="escape-wave"/><div className="site-width escape-inner"><div className="escape-copy"><span className="eyebrow"><Compass size={15}/> MOD: KAÇIŞ</span><h2>BİRAZ<br/><em>OFFLINE</em><br/>OLSAN?</h2><p>Yeni rotalar. Uzun kahvaltılar.<br/>“İyi ki gelmişim” dedirten yerler.</p><Link href={categoryByKey('seyahat').path} className="outline-button">Rotayı değiştir <ArrowUpRight size={21}/></Link><span className="escape-caption">→ Şehirden çıkış bu tarafta.</span></div><div className="escape-photos"><Link href={travel.path} className="postcard"><div className="postcard-image"><Photo article={travel}/><span className="postcard-label">KOS’TAN BİR NOT</span></div><div><h3>Modern seyahatin<br/>yeni lüksü: <em>özgürlük.</em></h3><ArrowUpRight size={24}/></div></Link><Link href={articleByKey('bodrum-boat').path} className="escape-circle"><Photo article={articleByKey('bodrum-boat')}/><span>MAVİNİN<br/>PEŞİNDEN <ArrowUpRight size={22}/></span></Link><span className="escape-stamp" aria-hidden="true">DAHA AZ YÜK<br/><strong>DAHA ÇOK<br/>HAYAT.</strong></span></div></div><Wave className="escape-bottom"/></section>
 <section className="site-width culture-section"><SectionHeading title="BUNU" accent="KONUŞALIM." eyebrow="KÜLTÜRÜN TAM ORTASINDAN" link={categoryByKey('ajanda')}/><div className="culture-spread"><article className="culture-main"><Link href={articleByKey('istanbula-reverans').path} className="culture-photo"><Photo article={articleByKey('istanbula-reverans')}/><span>BAŞKA BİR<br/><em>İSTANBUL</em></span><i aria-hidden="true">BAKIŞINI<br/>DEĞİŞTİR.</i></Link><div className="culture-main-copy"><span className="eyebrow">SANAT & FOTOĞRAF</span><h3><Link href={articleByKey('istanbula-reverans').path}>Aynı şehir. Bin farklı hikâye. İstanbul’a bir reverans.</Link></h3><Meta article={articleByKey('istanbula-reverans')}/></div></article><div className="culture-column"><StoryCard article={articleByKey('ben-bohmer')} variant="music-card"/><div className="culture-headphone"><Headphones aria-hidden="true"/><span>Sesini<br/><em>biraz aç.</em></span></div><StoryCard article={articleByKey('ozge-gurkan')} variant="art-row"/></div></div></section>
 <section className="feel-good-section"><div className="site-width"><div className="feel-good-heading"><div><span className="eyebrow">KENDİNE İYİ GELEN ŞEYLER</span><h2>MODUNU <span>YÜKSELT.</span></h2></div><Link className="all-link" href={categoryByKey('wellness').path}>Bir mola ver <ArrowUpRight size={20}/></Link></div><div className="feel-good-grid"><StoryCard article={articleByKey('coffee')} variant="feel-circle"/><StoryCard article={articleByKey('smoothies')} variant="feel-square"/><StoryCard article={articleByKey('hurrem-sultan-hamami')} variant="feel-arch"/></div></div></section>
 <section className="site-width topic-dock"><div><span className="eyebrow">BİR SONRAKİ TAKINTIN?</span><h2>MERAKINI<br/>SEÇ.</h2></div><div>{['celebrity','moda','seyahat','sanat','wellness','mekan'].map(key=><Link key={key} href={categoryByKey(key).path}>{categoryByKey(key).name}<ArrowUpRight size={22}/></Link>)}</div></section>
 </main></Shell>;
}
function Breadcrumb({category,article=false}:{category:Category;article?:boolean}) {return <nav className="breadcrumb" aria-label="İçerik yolu"><Link href="/">Ana sayfa</Link><ChevronRight size={13}/>{category.parent&&<><Link href={categoryByKey(category.parent).path}>{categoryByKey(category.parent).name}</Link><ChevronRight size={13}/></>}{article?<Link href={category.path}>{category.name}</Link>:<span aria-current="page">{category.name}</span>}</nav>}
export function CategoryPage({category,page=1}:{category:Category;page?:number}) {
 const all=forCategory(category);const count=Math.max(1,Math.ceil(all.length/6));const current=Math.min(Math.max(page,1),count);const posts=all.slice((current-1)*6,current*6);
 const siblings=categories.filter(c=>c.parent===category.key||category.parent&&c.parent===category.parent);
 return <Shell><main id="icerik" className="category-main" data-channel={category.key}><section className="category-banner"><div className="site-width"><Breadcrumb category={category}/><div className="category-title-row"><div><span className="eyebrow">HİPİNUP DOSYALARI / 0{categories.indexOf(category)%9+1}</span><h1>{category.name}<span>!</span></h1></div><div className="category-description"><Squiggle/><p>{category.description}</p></div></div><nav className="category-pills" aria-label={`${category.name} konuları`}>{(siblings.length?siblings:categories.filter(c=>c.key==='yasam'||c.key==='ajanda'||c.key==='populer')).map(c=><Link aria-current={c.key===category.key?'page':undefined} key={c.key} href={c.path}>{c.name}<ArrowUpRight size={15}/></Link>)}</nav></div><Wave className="category-wave"/></section>
 <div className="site-width">{posts.length>0?<><div className="archive-count"><span><Asterisk size={17}/> {all.length} HİKÂYE, BOLCA KEŞİF</span><span>Arşivden · Yayın tarihine göre</span></div>{current===1&&posts.length>1?<div className="category-feature-grid"><StoryCard article={posts[0]} variant="feature" priority/><div className="category-side"><span className="hand-note">Bunları da kaçırma.</span>{posts.slice(1,3).map((a,i)=><StoryCard article={a} key={a.key} variant="archive-side" index={i+1} priority/>)}</div></div>:null}<div className="archive-grid">{(current===1&&posts.length>1?posts.slice(3):posts).map((a,i)=><StoryCard key={a.key} article={a} index={i}/>)}</div>{count>1&&<Pagination aria-label="Arşiv sayfaları" className="archive-pagination"><PaginationContent>{current>1&&<PaginationItem><PaginationLink size="default" href={`${category.path}?page=${current-1}`}><ChevronLeft size={17}/> Önceki</PaginationLink></PaginationItem>}{Array.from({length:count},(_,i)=><PaginationItem key={i}><PaginationLink isActive={current===i+1} href={`${category.path}?page=${i+1}`}>{i+1}</PaginationLink></PaginationItem>)}{current<count&&<PaginationItem><PaginationLink size="default" href={`${category.path}?page=${current+1}`}>Sonraki <ChevronRight size={17}/></PaginationLink></PaginationItem>}</PaginationContent></Pagination>}</>:<div className="archive-empty"><span className="empty-symbol">up!</span><h2>YENİ HİKÂYELERE<br/>YER AÇIYORUZ.</h2><p>Bu seçkide henüz bir yazı yok. Merakını başka bir yöne çevirebilirsin.</p><Link className="blue-button" href="/konu/yasam/">Yaşamı keşfet <ArrowUpRight size={18}/></Link></div>}
 <AdSlot format="leaderboard" className="archive-ad"/>
 <section className="archive-discovery"><SectionHeading title="DAHA" accent="NELER VAR."/><div className="three-grid">{orderedArticles.filter(a=>!all.some(b=>b.key===a.key)).slice(0,3).map(a=><StoryCard article={a} key={a.key}/>)}</div></section></div></main></Shell>;
}
const travelSummary=['Bagaj, paket ve eşya saklama hizmetleri seyahat planının bir parçasına dönüşüyor.','Kos Box, adada teslimat adresi ve geçici depolama arayanlara bir seçenek sunuyor.','Yazının odağı: küçük lojistik sorunlara daha az, deneyime daha çok zaman ayırmak.'];
function ArticleTitle({article}:{article:Article}) {return article.key==='modern-travel'?<h1><small>Modern seyahatin yeni lüksü:</small>Bavul taşımak değil,<br/><em>özgür hareket edebilmek.</em></h1>:<h1>{article.title}</h1>}
export function ArticlePage({article}:{article:Article}) {
 const category=articleCategory(article);const content=bodies[article.key]||[];
 const related=articles.filter(a=>a.key!==article.key&&a.tags.some(t=>article.tags.includes(t))).slice(0,3);
 const more=related.length>=3?related:articles.filter(a=>a.key!==article.key).slice(0,3);
 const sections=content.map((b,i)=>({b,i})).filter(({b})=>b.type==='h2'||b.type==='h3');
 const isTravel=article.key==='modern-travel';
 const adAfter=content.length>=8?Math.min(9,Math.floor(content.length*.42)):-1;
 const pullQuote=isTravel?'Daha az yük. Daha fazla özgürlük.':article.excerpt;
 return <Shell><main id="icerik" className="article-main" data-channel={category.key}>
 <section className="article-cover"><div className="site-width"><Breadcrumb category={category} article/><div className="article-cover-grid"><header className="article-heading"><Link className="article-category" href={category.path}>{category.name}<ArrowUpRight size={17}/></Link><ArticleTitle article={article}/><p className="article-deck">{article.excerpt}</p><div className="article-byline"><div className="author-avatar">h.</div><div><strong>{article.author}</strong><span><time dateTime={article.date}>{dateLabel(article.date)}</time> · {article.minutes} dk okuma</span></div></div><ReaderActions articleKey={article.key}/></header><figure className={`article-cover-photo article-photo-${article.key}`}><Photo article={article} priority/><span className="article-photo-stamp" aria-hidden="true">{isTravel?<>AZ YÜK.<br/>ÇOK HAYAT.</>:<>MERAK<br/>ETMEYE<br/>DEVAM.</>}</span><figcaption>HİPİNUP ARŞİVİ / {category.name.toLocaleUpperCase('tr')}</figcaption></figure></div></div><Wave className="article-cover-wave"/></section>
 <ReadingProgress title={article.title}/>
 <div className="site-width"><div className="article-layout"><aside className="article-toc"><div className="sticky-toc"><span className="eyebrow">HİKÂYEYE DAL</span><h2>Bu<br/><em>yazıda.</em></h2><Squiggle/>{sections.length?sections.map(({b,i},n)=><a href={`#bolum-${i}`} key={i}><span>{String(n+1).padStart(2,'0')}</span>{b.text}</a>):<a href="#yazi"><span>01</span>Hikâyeyi oku</a>}<Link className="back-category" href={category.path}>{category.name} dosyası <ArrowUpRight size={18}/></Link></div></aside>
 <article id="yazi" className="article-body"><aside className="story-brief"><span className="brief-tag"><Asterisk size={19}/> HİKÂYENİN ÖZÜ</span>{isTravel?<ul>{travelSummary.map(t=><li key={t}>{t}</li>)}</ul>:<p>{article.excerpt}</p>}</aside>{content.length?content.map((block,i)=><div className="article-flow-block" key={i}>{block.type==='h2'||block.type==='h3'?<h2 id={`bolum-${i}`}><span>{String(sections.findIndex(s=>s.i===i)+1).padStart(2,'0')}</span>{block.text}</h2>:block.type==='li'?<p className="article-list-item">{block.text}</p>:<p className={i===0?'opening-paragraph':undefined}>{block.text}</p>}{i===Math.min(6,content.length-1)&&<aside className="article-pullout"><span className="pullout-mark" aria-hidden="true">“</span><p>{pullQuote}</p><Squiggle/></aside>}{i===adAfter&&<AdSlot format="rectangle" className="article-inline-ad"/>}</div>):<div className="archive-excerpt"><p>Bu hikâyenin tamamına Hipinup arşivindeki özgün yayınından ulaşabilirsin.</p><a href={`https://hipinup.com${article.path}`} className="all-link" target="_blank" rel="noreferrer">Arşivdeki yazıyı oku <ArrowUpRight size={18}/></a></div>}
 {article.key==='tommy-t-wave'&&<div className="article-gallery"><img src="/images/tommy-alternate-2.webp" alt="Tommy Hilfiger kampanyasından stil fotoğrafları" width={748} height={500} loading="lazy"/><img src="/images/tommy-alternate-3.webp" alt="Tommy Hilfiger kampanyasından diğer kombinler" width={748} height={500} loading="lazy"/><span>Kampanyadan stil notları / Hipinup arşivi</span></div>}
 <div className="article-end"><span>HİKÂYE BİTTİ.<br/><em>Merak devam.</em></span><Asterisk aria-hidden="true"/></div><div className="article-tags">{article.tags.map(key=><Link key={key} href={categoryByKey(key).path}>#{categoryByKey(key).name}</Link>)}</div><div className="article-editor"><div className="author-avatar">h.</div><div><strong>{article.author}</strong><p>Hayatın içinden, kültürün peşinden.</p></div></div></article>
 <aside className="article-sidebar"><AdSlot format="halfpage" className="article-rail-ad"/><div className="sidebar-heading">BİR DE<br/><span>BUNA BAK.</span></div>{more.slice(0,2).map(a=><StoryCard key={a.key} article={a}/>)}<a href="#bulten" className="sidebar-newsletter"><Mail size={27}/><h3>FEED’DE<br/><em>KAYBOLMA.</em></h3><p>İyi hikâyeleri senin için toparlıyoruz.</p><span>Bülteni keşfet <ArrowUpRight size={18}/></span></a></aside></div>
 <section className="related-section"><div className="related-heading"><span className="eyebrow">DAHA YENİ BAŞLADIK.</span><h2>BİR HİKÂYE<br/><em>DAHA?</em></h2><Link href={category.path} className="round-link" aria-label={`${category.name} dosyasını aç`}><ArrowUpRight size={32}/></Link></div><div className="three-grid">{more.map((a,i)=><StoryCard key={a.key} article={a} index={i}/>)}</div></section></div></main></Shell>;
}
export function SearchPage({query}:{query:string}) {const results=orderedArticles.filter(a=>(a.title+' '+a.originalTitle+' '+a.excerpt+' '+a.tags.map(t=>categoryByKey(t).name).join(' ')).toLocaleLowerCase('tr').includes(query.trim().toLocaleLowerCase('tr')));return <Shell><main id="icerik" className="site-width search-page"><span className="eyebrow">MERAKININ PEŞİNDEN.</span><h1>“{query}”</h1><p>{results.length} hikâye bulundu.</p><form action="/" className="page-search"><input type="search" name="s" defaultValue={query} aria-label="Aranacak kelime" placeholder="Neyi merak ediyorsun?"/><button className="blue-button" type="submit">Ara <ArrowRight size={18}/></button></form>{results.length?<div className="three-grid">{results.map(a=><StoryCard article={a} key={a.key}/>)}</div>:<div className="archive-empty"><h2>BAŞKA BİR KELİME<br/>DENEYELİM.</h2><p>“Moda”, “seyahat” veya “İstanbul” ile keşfe başlayabilirsin.</p><Link className="all-link" href="/">Ana sayfaya dön <ArrowUpRight size={18}/></Link></div>}</main></Shell>}
